### ISSUE TITLE
testimonials

### ISSUE THREAD

**Issue by bradgarropy** [bradgarropy/bradgarropy.com#126]
Quotes from others about working with me.
Put them on the `hire-me` page.

> I've loved collaborating with Brad since meeting him on Twitch. I've learned so much from him in 1:1 conversations, doing live streams together, his YouTube videos, etc. He has lots of knowledge as a Web Developer and is eager to share it with the community. The biggest downside to his content is that not enough people know about it yet!
> \- James Quick

> I've been blown away by the quality of your content.
> Really appreciate it, keep it up 🙏🏼
> \- [Scott Spence](https://twitter.com/spences10/status/1285306227757654025)

> You’re exceptionally talented at developing awesome websites. The level of mentorship and community-oriented camaraderie that you bring to the table is unprecedented. People are doing themselves a favor by following your work.
> \- [Todd Austin](https://twitter.com/austintoddj/status/1285378704840040448)

> Brad has a passion of not only learning the newest tech and programming but he also shares that passion with others in his stream. The one thing that stands out besides his passion to learn and share, is his meticulous work ethic and attention to detail, especially with accessibility. I don't see a lot of developers that focus at all on accessibility and Brad does that and that is why I respect him highly as a developer that knows his stuff.
> \- Todd Libby

> I really like the pace and tone of your videos. They are very relaxed but still dense with information. Looking forward to the next one!
> \- Drew Conley

> Your tutorial videos are clear and concise. Their production value is top notch. Well done my dude. 👍🏻
> \- [Andrew Worcester](https://twitter.com/amwmedia/status/1286654161929592833)

> Brad is an incredible example of hard work, ingenuity, and creativity. I've seen Brad day in and day out grind at his passion. You can tell he has a love for what he does and a deep understanding of the subjects he is working on. I recently had the opportunity to use Brads npm package useCountdown to write one of my articles and it worked seamlessly. I would recommend Brad for anything.
> \- [Steven Hofheins](https://twitter.com/Steven__Creates)

**Comment by StevenCreates** [comment]
Brad is an incredible example of hard work, ingenuity, and creativity. I've seen Brad day in and day out grind at his passion. You can tell he has a love for what he does and a deep understanding of the subjects he is working on. I recently had the opportunity to use Brads npm package useCountdown to write one of my articles and it worked seamlessly. I would recommend Brad for anything.
