### ISSUE TITLE
Generating bundle fails with `npm run start`

### ISSUE THREAD

**Issue by austintoddj** [bradgarropy/bradgarropy.com#179]
On a fresh install, after running `npm install && npm run start` I get the following error:

<img width="378" alt="Screen Shot 2021-01-22 at 1 34 34 PM" src="https://user-images.githubusercontent.com/8037011/105536993-d870b380-5cb6-11eb-9418-bd260faae967.png">

Thoughts?

**Comment by bradgarropy** [comment]
What version of `node` are you running?

```bash
$ node --version
v12.18.3
```

**Comment by austintoddj** [comment]
Currently on 15.5.0

**Comment by bradgarropy** [comment]
I updated to `v15.6.0` and still couldn't reproduce.

Does the following command work?
```bash
rm -rf .cache/ public/ ; npm run build
```

**Comment by austintoddj** [comment]
Welp, should have run `npm run build`. Didn't do that. 

Now that I did, it's a different error.

<img width="1271" alt="Screen Shot 2021-01-22 at 2 55 18 PM" src="https://user-images.githubusercontent.com/8037011/105545646-f2fc5a00-5cc1-11eb-85a8-dca788d2ae5a.png">

**Comment by bradgarropy** [comment]
Looks like you might be using `yarn` instead of `npm`? Try clearing out everything, reinstalling, and rebuilding.

```bash
rm -rf .cache/ public/ package-lock.json node_modules/
npm install
npm run build
npm start
```

**Comment by austintoddj** [comment]
Still hitting the errors unfortunately. Since it isn't reproducible, I'll close it out. 

Must be something with my setup.
