### ISSUE TITLE
Blog post images in dark mode

### ISSUE THREAD

**Issue by closetgeekshow** [bradgarropy/bradgarropy.com#305]
Suggestion: Maybe have a white background color for images enforced on dark mode? 

I just read the boredom / motivation correlation on your blog and turned on the dark mode at the start as it's my preference. 

It wasn't until I flipped on the light mode just to see it that I noticed there were images in the post. In this case black lines on what I assume is a transparent background, making them just look like black space in dark mode.

**Comment by bradgarropy** [comment]
Thanks for telling me about the bug! I fixed it in #306.

**Comment by bradgarropy** [comment]
@all-contributors please add @closetgeekshow for finding a bug

**Comment by closetgeekshow** [comment]
well look at that, my first contribution. Thanks!
