### ISSUE TITLE
Deployment Failure Caused by Primary Branch Name Modification

### ISSUE THREAD

**Issue by EliasAfara** [bradgarropy/bradgarropy.com#382]
It seems that after the modification of changing the primary branch name to main, the deployment to Vercel failed. Thus, when the user clicks on the `💻 edit on github` it will redirect the user using this link: `https://github.com/bradgarropy/bradgarropy.com/edit/master/content/posts/new-macbook-setup.md`

![image](https://github.com/bradgarropy/bradgarropy.com/assets/39487200/d8f59d0d-9cbf-4d93-8676-c1bf460a6d1e)

**Comment by bradgarropy** [comment]
Thanks @EliasAfara! You're exactly right. I went over to Vercel and bumped the latest build to `production`, and everything seems to be working.

Can you confirm from your end? (Make sure to clear cache when checking).

**Comment by EliasAfara** [comment]
Yes, now it's working properly. It's asking me to fork the repository. 👍🏻

**Comment by bradgarropy** [comment]
@all-contributors please add @EliasAfara for bug
